# Generated by Django 4.1.3 on 2022-12-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="photo",
            field=models.ImageField(upload_to="photo/%Y/%m/%d/"),
        ),
    ]
